# prospector configuration file

---

output-format: grouped

strictness: veryhigh
doc-warnings: true
test-warnings: true
member-warnings: false

ignore-patterns:
  - ^tests/.*
  - ^build/.*
  - ^dist/.*

dodgy:
  run: true

mccabe:
  options: {max-complexity: 10}
  run: true

pyroma:
    run: true

pep8:
    full: true

pydocstyle:
    run: true

pyflakes:
    run: true

pep257:
    # see http://pep257.readthedocs.io/en/latest/error_codes.html
    disable: [
        D203,  # 1 blank line required before class docstring
        D213,  # Multi-line docstring summary should start at the second line
    ]

